template_path: "marketplace-dynamo.yaml"
stack_name: "marketplace-dynamo"
dependencies:
  - "prod/essentials.yaml"
  - "prod/synapse-oidc-idp.yaml"
parameters:
  # InstanceRoleArn from https://github.com/Sage-Bionetworks/synapse-login-aws-infra/blob/prod/templates/app.yaml
  SynapseLoginInstanceRole: !stack_output_external synapse-login-scipoolprod::InstanceRole
