template_path: "remote/sc-enduser-iam.yaml"
stack_name: "sc-enduser-iam"
dependencies:
  - "prod/essentials.yaml"
hooks:
  before_create:
    - !cmd "curl https://s3.amazonaws.com/aws-service-catalog-reference-architectures/iam/sc-enduser-iam.yml --create-dirs -o templates/remote/sc-enduser-iam.yaml"
  before_update:
    - !cmd "curl https://s3.amazonaws.com/aws-service-catalog-reference-architectures/iam/sc-enduser-iam.yml --create-dirs -o templates/remote/sc-enduser-iam.yaml"
