template_path: "remote/sc-emr-launchrole.yaml"
stack_name: "sc-emr-launchrole"
dependencies:
  - "prod/essentials.yaml"
hooks:
  before_create:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-service-catalog-reference-architectures/master/iam/sc-emr-launchrole.yml --create-dirs -o templates/remote/sc-emr-launchrole.yaml"
  before_update:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-service-catalog-reference-architectures/master/iam/sc-emr-launchrole.yml --create-dirs -o templates/remote/sc-emr-launchrole.yaml"
