template_path: "remote/sc-portfolio-vpc.yaml"
stack_name: "sc-portfolio-vpc"
dependencies:
  - "prod/sc-ec2vpc-launchrole.yaml"
  - "prod/sc-enduser-iam.yaml"
parameters:
  LaunchRoleName: "SCEC2LaunchRole"
  CreateEndUsers: "No"
  LinkedRole1: ""
  LinkedRole2: ""
  RepoRootURL: "https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/scipoolprod-sc-lib-infra/master/"
hooks:
  before_create:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/scipoolprod-sc-lib-infra/master/vpc/sc-portfolio-vpc.yaml --create-dirs -o templates/remote/sc-portfolio-vpc.yaml"
  before_update:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/scipoolprod-sc-lib-infra/master/vpc/sc-portfolio-vpc.yaml --create-dirs -o templates/remote/sc-portfolio-vpc.yaml"
