template_path: "remote/sc-rds-launchrole.yaml"
stack_name: "sc-rds-launchrole"
dependencies:
  - "prod/essentials.yaml"
hooks:
  before_create:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-service-catalog-reference-architectures/master/iam/sc-rds-launchrole.yaml --create-dirs -o templates/remote/sc-rds-launchrole.yaml"
  before_update:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-service-catalog-reference-architectures/master/iam/sc-rds-launchrole.yaml --create-dirs -o templates/remote/sc-rds-launchrole.yaml"
