template_path: "remote/sc-s3-launchrole.yaml"
stack_name: "sc-s3-launchrole"
dependencies:
  - "prod/essentials.yaml"
hooks:
  before_create:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/scipoolprod-sc-lib-infra/master/iam/sc-s3-launchrole.yaml --create-dirs -o templates/remote/sc-s3-launchrole.yaml"
  before_update:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/scipoolprod-sc-lib-infra/master/iam/sc-s3-launchrole.yaml --create-dirs -o templates/remote/sc-s3-launchrole.yaml"
