template_path: "idp-marketplace-policy.yaml"
stack_name: "idp-marketplace-policy"
dependencies:
  - "develop/essentials.yaml"
  - "develop/synapse-oidc-idp.yaml"
parameters:
  # InstanceRoleArn from https://github.com/Sage-Bionetworks/synapse-login-aws-infra/blob/develop/templates/app.yaml
  SynapseLoginInstanceRoleArn: !stack_output_external synapse-login-scipooldev::InstanceRoleArn
