template_path: remote/maintenance.yaml
stack_name: prod-default-maintenance-window
stack_tags:
  Department: "Platform"
  Project: "Infrastructure"
  OwnerEmail: "it@sagebase.org"
hooks:
  before_launch:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/maintenance.yaml --create-dirs -o templates/remote/maintenance.yaml"
