Description: Invoke permission for SsmParam Lambda Function
AWSTemplateFormatVersion: 2010-09-09

Resources:
  InvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !ImportValue
        'Fn::Sub': '${AWS::Region}-cfn-ssm-param-macro-SsmParamFunctionArn'
      Action: lambda:InvokeFunction
      Principal: !Ref 'AWS::AccountId'
      SourceArn: !ImportValue
        'Fn::Sub': '${AWS::Region}-sc-ec2vpc-launchrole-LaunchRoleArn'
