Description: "Policy that lets the Synapse login role resolve marketplace customer"

Resources:
  ResolveCustomerMarketplacePolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Sid: ResolveCustomerMarketplace
            Effect: Allow
            Action: "aws-marketplace:ResolveCustomer"
            Resource: "*"

Outputs:
  ResolveCustomerMarketplacePolicyArn:
    Description: Managed policy allowing access to the ResolveCustomer AWS Marketplace API
    Value: !Ref ResolveCustomerMarketplacePolicy
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-ResolveCustomerMarketplacePolicyArn'
