Description: IAM accounts for service catalog
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  InitNewUserPassword:
    Type: String
    NoEcho: true
Resources:
  # !! IMPORTANT !! - AWS API will refuse to remove users that have attached resources.
  # Therefore you must do the following before deleting them from this file:
  # 1. Detach or remove the following user resources: login profile, attached
  #    MFA device, access-keys, ssh-keys, and policies.
  # 2. Detach the user from all groups.
  JoeSmithUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: joe.smith@sagebase.org
      Groups:
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-accounts-AllUsersGroup'
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-sc-enduser-iam-ServiceCatalogEndusers-GroupName'
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-sc-enduser-development-iam-ServiceCatalogDevelopmentEndusers-GroupName'
      LoginProfile:
        Password: !Ref InitNewUserPassword
        PasswordResetRequired: true
  TthyerTestUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: tthyer.test@sagebase.org
      Groups:
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-accounts-AllUsersGroup'
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-sc-enduser-iam-ServiceCatalogEndusers-GroupName'
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-sc-enduser-development-iam-ServiceCatalogDevelopmentEndusers-GroupName'
      LoginProfile:
        Password: !Ref InitNewUserPassword
        PasswordResetRequired: true
  XengieDoanUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: "xengie.doan@sagebase.org"
      Groups:
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-accounts-AllUsersGroup'
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-sc-enduser-iam-ServiceCatalogEndusers-GroupName'
      LoginProfile:
        Password: !Ref InitNewUserPassword
        PasswordResetRequired: true
  BruceHoffUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: bruce.hoff@sagebase.org
      Groups:
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-accounts-AllUsersGroup'
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-sc-enduser-iam-ServiceCatalogEndusers-GroupName'
      LoginProfile:
        Password: !Ref InitNewUserPassword
        PasswordResetRequired: true
  MarcoMarascaUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: marco.marasca@sagebase.org
      Groups:
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-accounts-AllUsersGroup'
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-sc-enduser-iam-ServiceCatalogEndusers-GroupName'
      LoginProfile:
        Password: !Ref InitNewUserPassword
        PasswordResetRequired: true
  WilliamPoehlmanUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: william.poehlman@sagebase.org
      Groups:
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-accounts-AllUsersGroup'
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-sc-enduser-iam-ServiceCatalogEndusers-GroupName'
      LoginProfile:
        Password: !Ref InitNewUserPassword
        PasswordResetRequired: true
  DumindaAluthgamageUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: duminda.aluthgamage@sagebase.org
      Groups:
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-accounts-AllUsersGroup'
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-sc-enduser-iam-ServiceCatalogEndusers-GroupName'
      LoginProfile:
        Password: !Ref InitNewUserPassword
        PasswordResetRequired: true
  JamesEddyUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: james.eddy@sagebase.org
      Groups:
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-accounts-AllUsersGroup'
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-sc-enduser-iam-ServiceCatalogEndusers-GroupName'
      LoginProfile:
        Password: !Ref InitNewUserPassword
        PasswordResetRequired: true
  ThomasYuUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: thomas.yu@sagebase.org
      Groups:
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-accounts-AllUsersGroup'
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-sc-enduser-iam-ServiceCatalogEndusers-GroupName'
      LoginProfile:
        Password: !Ref InitNewUserPassword
        PasswordResetRequired: true
  VanessaBaronUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: vanessa.barone@sagebase.org
      Groups:
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-accounts-AllUsersGroup'
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-sc-enduser-iam-ServiceCatalogEndusers-GroupName'
      LoginProfile:
        Password: !Ref InitNewUserPassword
        PasswordResetRequired: true
  LarssonOmbergUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: larsson.omberg@sagebase.org
      Groups:
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-accounts-AllUsersGroup'
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-sc-enduser-iam-ServiceCatalogEndusers-GroupName'
      LoginProfile:
        Password: !Ref InitNewUserPassword
        PasswordResetRequired: true
  JakeGockleyUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: jake.gockley@sagebase.org
      Groups:
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-accounts-AllUsersGroup'
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-sc-enduser-iam-ServiceCatalogEndusers-GroupName'
      LoginProfile:
        Password: !Ref InitNewUserPassword
        PasswordResetRequired: true
  KennethDailyUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: kenneth.daily@sagebase.org
      Groups:
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-accounts-AllUsersGroup'
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-sc-enduser-iam-ServiceCatalogEndusers-GroupName'
      LoginProfile:
        Password: !Ref InitNewUserPassword
        PasswordResetRequired: true
  KelseyMontgomeryUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: kelsey.montgomery@sagebase.org
      Groups:
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-accounts-AllUsersGroup'
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-sc-enduser-iam-ServiceCatalogEndusers-GroupName'
      LoginProfile:
        Password: !Ref InitNewUserPassword
        PasswordResetRequired: true
  AnnaGreenwoodUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: anna.greenwood@sagebase.org
      Groups:
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-accounts-AllUsersGroup'
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-sc-enduser-iam-ServiceCatalogEndusers-GroupName'
      LoginProfile:
        Password: !Ref InitNewUserPassword
        PasswordResetRequired: true
  XindiGuoUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: xindi.guo@sagebase.org
      Groups:
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-accounts-AllUsersGroup'
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-sc-enduser-iam-ServiceCatalogEndusers-GroupName'
      LoginProfile:
        Password: !Ref InitNewUserPassword
        PasswordResetRequired: true
  LeaMartinUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: lea.martin@sagebase.org
      Groups:
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-accounts-AllUsersGroup'
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-sc-enduser-iam-ServiceCatalogEndusers-GroupName'
      LoginProfile:
        Password: !Ref InitNewUserPassword
        PasswordResetRequired: true
