Description: Template Constraint for VPC.
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  PortfolioID:
    Type: String
    Description: >-
      Id of the Service Catalog Portfolio where this constraint will be used
  ProductID:
    Type: String
    Description: >-
      Id of the Service Catalog Product to which this constraint will be applied
Resources:
  TemplateConstraint:
    Type: AWS::ServiceCatalog::LaunchTemplateConstraint
    Properties:
      AcceptLanguage: en
      Description: Limit VPC selection.
      PortfolioId: !Ref PortfolioID
      ProductId: !Ref ProductID
      Rules: >-
        {
          "LimitVPC": {
            "Assertions": [
              {
                "Assert": {
                  "Fn::Equals": [
                    {
                      "Ref": "VPC"
                    },
                    "vpc-0d92dc681a4078458"
                  ]
                },
                "AssertDescription": "VPC must be vpc-0d92dc681a4078458"
              }
            ]
          },
          "LimitSubnets": {
            "Assertions": [
              {
                "Assert": {
                  "Fn::EachMemberEquals": [
                    {
                      "Fn::ValueOfAll": [
                        "AWS::EC2::Subnet::Id",
                        "VpcId"
                      ]
                    },
                    {
                      "Ref": "VPC"
                    }
                  ]
                },
                "AssertDescription": "Every member of all subnet type parameters should belong to the vpc specified"
              }
            ]
          }
        }
