template_path: "sc-tag-options-dev.j2"
stack_name: "sc-tag-options-dev"
dependencies:
  - "dev/sc-portfolio-ec2-development.yaml"
  - "dev/sc-portfolio-ec2-development-tthyer.yaml"
  - "dev/sc-portfolio-s3-basic-development.yaml"
sceptre_user_data:
  Departments:
    - "Test"
  Projects:
    - "Test"
  ProductIDs:
    - "port-faptnwqjadgnu"   # Development EC2 portfolio
    - "port-xdumjjreeuohg"   # Development S3 basic portfolio
    - "port-s6goadrhh5mpi"   # Development Tthyer sandbox portfolio
